### ISSUE TITLE
site_version pointing to wrongly

### ISSUE THREAD

**Issue by adambrgmn** [steenbergen-design/trellis-action#4]
Hi again! I'm having a really strange issue with SHA refs not existing.

I setup my action/site to use what you've done (`branch: "{{ site_version | default('master') }}"` in `group_vars`). But it always seemed to fail. When setting the branch to master (or any other remote branch) it worked fine. So I came to the conclusion that there is nothing wrong with `ssh` keys or similar.

After some digging and logging with Trellis I found out that the [`sha` used](https://github.com/steenbergen-design/trellis-action/blob/501450d2495a0e9aca0776c0f238ebd6b7728f7c/index.js#L118) (originating from `process.env.GITHUB_SHA`) was "not correct".

```
fatal: reference is not a tree: {sha}
```

After [finding this](https://github.community/t5/GitHub-Actions/GITHUB-SHA-but-how-to-get-the-latest-commit-reference-on-a/td-p/40873,) and adding the step below to my action, I got it confirmed. The env variable `GITHUB_SHA` is – at least in my case – pointing at something not available.

```yml
- name: sha
    run: |
      echo ${{ github.event.pull_request.head.sha }}
      echo $GITHUB_SHA
```

So I was wondering if it's possible to take another approach? I'm not sure if the `@actions/github` package works inside the docker env. But if so that could be used to get the `sha` used above.

```js
const github = require('@actions/github');
const sha = github.event.pull_request.head.sha;
```

Or do you think I might have some setup that causes these issues?

**Comment by adambrgmn** [comment]
I did some further investigation and it seems like `GITHUB_SHA` is working properly when used in `push` triggered actions, but not in actions triggered on `pull_request`.

Here's my use case:
I have a staging and a prod site. And I want to be able to deploy a PR on staging if needed. I imagine doing this by setting a label (e.g. "deploy staging") on the PR.

I can achive this with the following setup:

```yml
name: Deploy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  deploy:
    runs-on: ubuntu-16.04
    name: Deploy
    steps:
      - name: setup project
        uses: actions/checkout@v1

      - name: setup ssh
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: ${{ github.workspace }}/ssh-auth.sock

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: deploy staging
        uses: steenbergen-design/trellis-action@v1.0.0
        if: contains(github.event.pull_request.labels.*.name, 'deploy staging')
        with:
          vault_password: ${{ secrets.VAULT_PASS }}
          site_env: staging
          site_name: www.example.com
```

**Comment by Xilonz** [comment]
Hmm. I haven't seen this issue before. I use Dependabot to bump packages and that triggers a workflow with this action, and that has been working fine. The best solution looks to be adding another `with` or env variable. I believe ansible will take the systems env variables, so we might be able to remove the whole [```-e site_version = ...```](https://github.com/steenbergen-design/trellis-action/blob/master/index.js#L118) ansible argument in the future.

**Comment by adambrgmn** [comment]
> Hmm. I haven't seen this issue before. I use Dependabot to bump packages and that triggers a workflow with this action, and that has been working fine. The best solution looks to be adding another `with` or env variable. I believe ansible will take the systems env variables, so we might be able to remove the whole [`-e site_version = ...`](https://github.com/steenbergen-design/trellis-action/blob/master/index.js#L118) ansible argument in the future.

@Xilonz But I'm guessing that you are running the action on `push` events and not on `pull_request`, right?

```yml
name: whatever
on:
  - push # in these actions GITHUB_SHA is correct
  - pull_request # here GITHUB_SHA is pointing at something very different and unreachable from the outside
```

I've fiddled with it and I'm now certain that the env variable `GITHUB_SHA` is not usable when running this action on `pull_request`.

Regarding adding a new `with` statement or `env` variable I'm not sure what you mean. I tried this:

```yml
- uses: steenbergen-design/trellis-action@v1
  with: 
    ...
  env:
    GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
```

But I can't seem to override that env variable. Github overwrites it anyhow.

**Comment by adambrgmn** [comment]
Or if we want to be able to configure it from the outside we could accept `site_version` (or any other key) as input:

```yml
inputs:
  site_version:
    description: 'Branch or SHA that will be deployed by Trellis'
    required: false
    default: ${{ github.sha }}
```

And if I run this on a pr I would simply provide this config:

```yml
- uses: steenbergen-design/trellis-action@v1
  with: 
    site_version: ${{ github.event.pull_request.head.sha }}
```

And the code would be something like this:

```js
const deploy = await run_playbook(site_name, site_env, core.getInput('site_version'));
```
