### ISSUE TITLE
Ansible Galaxy Roles not installed

### ISSUE THREAD

**Issue by vburlak** [steenbergen-design/trellis-action#6]
Hey guys, I'm using https://github.com/ItinerisLtd/trellis-slack-webhook-notify-during-deploy for deployment complete messages in Slack.

And I got such issue during deploy:
```
TASK [deploy : include_tasks] **************************************************
  ---------------------------------------------------
 Could not find or access '/github/workspace/trellis/vendor/roles/trellis-
  slack-webhook-notify-during-deploy/tasks/main.yml' on the Ansible Controller.
  fatal: [staging]: FAILED! => {"reason": "Could not find or access '/github/workspace/trellis/vendor/roles/trellis-slack-webhook-notify-during-deploy/tasks/main.yml' on the Ansible Controller."}
```

It seems that roles from `galaxy.yml` not installed. Here is a task output with `verbose: true`: 
```
Install Galaxy Roles
Installing Galaxy Roles using galaxy.yml
```

I'm using: 
- official directory structure:
```
example.com/      # → Root folder for the project
├── .git/         # → Only one git repo
├── trellis/      # → Your clone of roots/trellis, directory name must be `trellis`
└── site/         # → A Bedrock-based WordPress site, directory name doesn't matter
```
- my job step
```
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: ${{ github.workspace }}/ssh-auth.sock

      - uses: steenbergen-design/trellis-action@master
        with:
          role_file: galaxy.yml
          vault_password: ${{ secrets.VAULT_PASS }}
          site_env: staging
          site_name: example.com 
          verbose: true
```
- Bedrock 1.14.1
- Trellis 1.4.0

I'm using the `steenbergen-design/trellis-action@master` because https://github.com/steenbergen-design/trellis-action/pull/5 has been merged without publishing a new release.
Also, I've tried to change `role_file: ${{ github.workspace }}/trellis/galaxy.yml` but with no luck.

Any thoughts on it?
Thanks!
